### PR TITLE
Alert users on bad blade files

### PR DESCRIPTION
**Pull request by szepeviktor**
print a simple error message
props. @iamgergo

### CODE REVIEW

**Comment by melihovv** [comment]
Error during View::compile() call is ignored because it is thrown almost in every blade file. Because we do not provide custom variables that are needed.
In your controller you make your view like the following
```php
view('dashboard', [
  'user' => $user,
  'stats' => $stats,
];
```
But in view:compile command we cannot pass those params, because we don't know anything about them.

For what reason do you want to see those error messages?

**Comment by szepeviktor** [comment]
Thank you for your answer.

Those views with errors are only compiled later at runtime (which triggers out monitoring system, as new PHP files are born)

**Comment by melihovv** [comment]
Hmm. Are you sure that those views are compiled later at runtime?
My experience says that they aren't.
Functionality of this package recently was built in laravel, see this [command](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Console/ViewCacheCommand.php). Maybe try that.

**Comment by szepeviktor** [comment]
> Are you sure that those views are compiled later at runtime?

Our monitoring script runs every hour and checks all files with new ctime or mtime.
I was opening this issue because of that.

**Comment by melihovv** [comment]
What laravel version do you use?
And if we will log those errors, how does it help us?

**Comment by szepeviktor** [comment]
v5.6.21

> And if we will log those errors, how does it help us?

Then we won't go blind and it will appear as soon as in the CI.

**Comment by szepeviktor** [comment]
>  Functionality of this package recently was built in laravel, see this command. Maybe try that.

Oh!!! :)
So we do not need your package??

**Comment by melihovv** [comment]
> So we do not need your package??

I suppose :)
If you will be satisfied with built in command, please, close this pr :)

**Comment by szepeviktor** [comment]
Thank you.

Does your package provide something more??

**Comment by melihovv** [comment]
I don't sure.
I did use this package in last year last time and I haven't used built-in view:cache command in laravel yet.
So I cannot say more. But in first look functionality looks the same :)

**Comment by szepeviktor** [comment]
OK

**Pull request closed without merging**
